const data = {
  products: [
    {
      name: 'Spinach large',
      slug: 'spinach-large',
      category: 'Greens',
      image: '/images/spinach-large.jpg',
      price: 10,
      countInStock: 10,
      brand: 'RaghavFarm',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality spinach',
    },
    {
      name: 'Spinach small',
      slug: 'spinach-small',
      category: 'Greens',
      image: '/images/spinach-small.jpg',
      price: 5,
      countInStock: 10,
      brand: 'RaghavFarm',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality spinach',
    },
    {
      name: 'Lettuce large',
      slug: 'lettuce-large',
      category: 'Greens',
      image: '/images/lettuce-large.jpg',
      price: 10,
      countInStock: 10,
      brand: 'RaghavFarm',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality Lettuce',
    },
    {
      name: 'Blueberry',
      slug: 'Blueberry',
      category: 'Fruits',
      image: '/images/blueberry.jpg',
      price: 10,
      countInStock: 10,
      brand: 'RaghavFarm',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality Blueberry',
    },
  ],
};

export default data;
